apiVersion: v1
kind: Service
metadata:
  name: node
spec:
  ports:
  - port: 3000
  type: LoadBalancer
  selector:
    app: node
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node
spec:
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      securityContext:
        runAsUser: 1000
      containers:
      - name: node
        image: node-example
        ports:
        - containerPort: 3000
