apiVersion: v1
kind: Service
metadata:
  name: nodejs-template-frontend
  labels:
    app: nodejs-template
    tier: frontend
spec:
  type: LoadBalancer
  selector:
    app: nodejs-template
    tier: frontend
  ports:
  - port: 80
    targetPort: http-server