env:
  commonjs: true
  es6: true
  node: true
  mocha: true
extends: 'eslint:recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2020
rules: {
  no-console: 0,
  prefer-arrow-callback: 2
}
