apiVersion: v1
kind: Service
metadata:
  name: nodejs-sample-backend
  labels:
    app: nodejs-sample
    tier: backend
spec:
  type: ClusterIP
  selector:
    app: nodejs-sample
    tier: backend
  ports:
  - port: 8080
    targetPort: http-server
