apiVersion: v1
kind: Service
metadata:
  name: python
spec:
  ports:
  - port: 5000
  type: LoadBalancer
  selector:
    app: python
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python
spec:
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      securityContext:
        runAsUser: 1000
      containers:
      - name: python
        image: python-reload
        ports:
        - containerPort: 5000
